# Generated by Django 2.0.1 on 2018-04-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_auto_20180429_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='negro', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='descripcion',
            field=models.CharField(default='', max_length=200),
        ),
    ]
