# Generated by Django 2.0.1 on 2018-04-29 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0004_renta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaVenta', models.DateField(auto_now_add=True)),
                ('FechaDeRecogida', models.DateField()),
                ('TallaNum', models.CharField(choices=[('talla1', '32'), ('talla2', '33'), ('talla3', '34'), ('talla4', '35'), ('talla5', '36'), ('talla6', '37'), ('talla7', '38'), ('talla8', '39'), ('talla9', '40'), ('talla10', '41'), ('talla11', '42'), ('talla12', '43'), ('talla13', '44'), ('talla14', '45'), ('talla15', '46'), ('talla16', '47'), ('talla17', '48'), ('talla18', '49'), ('talla19', '50')], default=1, max_length=9)),
                ('TallaMedida', models.CharField(choices=[('medida1', 'Corto'), ('medida2', 'Regular'), ('medida3', 'Largo')], default=1, max_length=9)),
                ('LugarRecogida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.Sastrerias')),
                ('Tuxedo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.Product')),
            ],
        ),
    ]
