# Generated by Django 2.0.1 on 2018-05-02 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0006_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='precio',
        ),
    ]
