# Generated by Django 2.0.1 on 2018-05-02 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0007_remove_orders_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='resource',
        ),
        migrations.AddField(
            model_name='purchase',
            name='resource',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pagina.Orders'),
        ),
    ]
