# Generated by Django 2.0.1 on 2018-05-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0008_auto_20180502_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='nombre_producto',
        ),
        migrations.AddField(
            model_name='orders',
            name='nombre_producto',
            field=models.ManyToManyField(blank=True, default=1, to='pagina.Product'),
        ),
    ]
