# Generated by Django 2.0.1 on 2018-05-03 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pagina', '0009_auto_20180502_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Purchase_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='purchaser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orders',
            name='tx',
            field=models.CharField(default='1', max_length=250),
        ),
    ]
