# Generated by Django 2.0.1 on 2018-05-03 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0011_orders_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='cantitad',
        ),
    ]
